### PR TITLE
Use lininfile module for umask 002 instead of writing a file.

### PR DESCRIPTION
**Pull request by ghost**
This makes the role more portable across different operating system
versions.

### CODE REVIEW

**Comment by ajsalminen** [comment]
Does this have some specific issues across debian versions? I'd rather go with a templated approach so that we fully specify what exactly is defined in the file.

**Comment by ghost** [comment]
yes, for example Stretch and Jessie has now APACHE_PID_FILE=/var/run/apache2$SUFFIX/apache2.pid (or something like that) instead of APACHE_PID_FILE=/var/run/apache2$SUFFIX.pid.

**Comment by ghost** [comment]
@ajsalminen what are the benefits of defining exactly what we want in the template file? Doing so adds quite a bit of work because each distribution and distribution's version might need its own template so I think going with that solution needs to have some strong benefits. Also we cannot then decide easily one day that we would like to use now this other X distribution for our servers because new template would have to be defined.

**Comment by ajsalminen** [comment]
It's true that accommodating different versions of a distribution can be some more work in the cases where the changes are small enough that lineinfile would just keep functioning but you often run into much more serious problems if your general approach is trying to adjust everything with something like lineinfile instead of providing a complete set of configuration for an application. I'd even say the more likely case is that the same configuration will function across versions of a distribution and you're in control of when and what to change.

lineinfile is fairly commonly considered to be something that you should avoid as much as possible. We're trying to manage the configuration state of a system and leaving parts unmanaged on purpose isn't generally helpful as it potentially just leads to not having a clear idea of what the configuration includes. Using lineinfile also would not help that much with compatibility between different distributions as they have wildly varying configuration layouts etc.
.

**Pull request closed without merging**
